FileVersion = 1
LastConfig = "Release"
LastPlatform = "Win64"
RecentFilesList = ["src\\KairosEngine.bf", "src\\WindowSystem.bf", "src\\Graphics\\GraphicsCommandList_Bindings.bf", "src\\Graphics\\GraphicsCommandList.bf", "src\\WindowSystem_Bindings.bf", "src\\Graphics\\GraphicsResource_Bindings.bf", "src\\Graphics\\GraphicsResource.bf", "src\\Graphics\\GraphicsSwapChain.bf", "src\\Graphics\\GraphicsSwapChain_Bindings.bf", "src\\Graphics\\GraphicsRenderTarget.bf", "src\\Graphics\\GraphicsCommandQueue.bf", "src\\Graphics\\GraphicsCommandAllocator.bf", "src\\Graphics\\GraphicsCommandAllocator_Bindings.bf", "src\\Graphics\\GraphicsFenceEvent.bf", "src\\Kernel.bf", "src\\Graphics\\GraphicsFenceEvent_Bindings.bf", "src\\Graphics\\GraphicsFence.bf", "src\\Graphics\\GraphicsFence_Bindings.bf", "src\\Graphics\\Rect.bf", "src\\Graphics\\ViewPort.bf"]

[MainWindow]
X = 526
Y = 166
Width = 1200
Height = 1024
ShowKind = "ShowMaximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 350.0
RequestedHeight = 200.0
SizePriority = 200.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 409.0
RequestedHeight = 200.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 115.0
TabIsPinned = false
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 150.0
RequestedHeight = 150.0
SizePriority = 150.0
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsSwapChain.bf"
TabWidth = 159.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsSwapChain.bf"
CursorPos = 723
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsSwapChain_Bindings.bf"
TabWidth = 213.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsSwapChain_Bindings.bf"
CursorPos = 795
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsRenderTarget.bf"
TabWidth = 175.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsRenderTarget.bf"
CursorPos = 116
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsCommandAllocator.bf"
TabWidth = 207.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsCommandAllocator.bf"
CursorPos = 335
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsCommandAllocator_Bindings.bf"
TabWidth = 262.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsCommandAllocator_Bindings.bf"
CursorPos = 371
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsFenceEvent.bf"
TabWidth = 160.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsFenceEvent.bf"
CursorPos = 149
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Kernel.bf"
TabWidth = 82.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Kernel.bf"
CursorPos = 346
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "WindowSystem_Bindings.bf"
TabWidth = 187.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\WindowSystem_Bindings.bf"
CursorPos = 184
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsFence_Bindings.bf"
TabWidth = 183.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsFence_Bindings.bf"
CursorPos = 513
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsFenceEvent_Bindings.bf"
TabWidth = 214.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsFenceEvent_Bindings.bf"
CursorPos = 514
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsFence.bf"
TabWidth = 129.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsFence.bf"
CursorPos = 228
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "WindowSystem.bf"
TabWidth = 133.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\WindowSystem.bf"
CursorPos = 880
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Rect.bf"
TabWidth = 70.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\Rect.bf"
CursorPos = 265
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "ViewPort.bf"
TabWidth = 96.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\ViewPort.bf"
CursorPos = 380
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsResource_Bindings.bf"
TabWidth = 204.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsResource_Bindings.bf"
CursorPos = 346
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsResource.bf"
TabWidth = 150.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsResource.bf"
CursorPos = 203
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsVertexBufferView.bf"
TabWidth = 194.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsVertexBufferView.bf"
CursorPos = 380
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsCommandQueue.bf"
TabWidth = 194.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsCommandQueue.bf"
CursorPos = 335
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsCommandQueue_Bindings.bf"
TabWidth = 248.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsCommandQueue_Bindings.bf"
CursorPos = 653
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsCommandList.bf"
TabWidth = 175.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsCommandList.bf"
CursorPos = 1650
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsCommandList_Bindings.bf"
TabWidth = 229.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsCommandList_Bindings.bf"
CursorPos = 2024
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "KairosEngine.bf"
TabWidth = 121.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\KairosEngine.bf"
CursorPos = 9957
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 1914.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Console"
TabWidth = 97.0
TabIsPinned = false
Type = "ConsolePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 99.0
TabIsPinned = false
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 300.0

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 86.0
TabIsPinned = false
Type = "WatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs.Items]]
EvalStr = ""

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Auto"
TabWidth = 77.0
TabIsPinned = false
Type = "AutoWatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 1914.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 97.0
TabIsPinned = false
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 105.0
TabIsPinned = false
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 111.0
TabIsPinned = false
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 90.0
TabIsPinned = false
Type = "OutputPanel"

[[BookmarkFolders]]
Title = ""

[OutputFilters]
ModuleLoadMessages = false
ModuleUnloadMessages = false
ProcessExitMessages = false
ThreadCreateMessages = false
ThreadExitMessages = false
SymbolLoadMessages = false
ProgramOutput = false
