FileVersion = 1
LastConfig = "Release"
LastPlatform = "Win64"
RecentFilesList = ["src\\KairosEngine.bf", "src\\Graphics\\GraphicsRootSignature_Bindings.bf", "src\\Graphics\\GraphicsRootSignature.bf", "src\\Graphics\\GraphicsDevice.bf", "src\\Graphics\\GraphicsDevice_Bindings.bf", "src\\Graphics\\RootSignatureFlags.bf", "src\\Graphics\\GraphicsSwapChain_Bindings.bf", "src\\Graphics\\GraphicsFenceEvent_Bindings.bf", "src\\Graphics\\GraphicsFence_Bindings.bf", "src\\Graphics\\GraphicsFactory.bf", "src\\Graphics\\GraphicsFenceEvent.bf", "src\\Graphics\\GraphicsFactory_Bindings.bf", "src\\Graphics\\FenceFlags.bf", "src\\Graphics\\CommandListType.bf", "src\\Graphics\\GraphicsFence.bf", "src\\Graphics\\GraphicsRenderTarget_Bindings.bf", "src\\Graphics\\GraphicsCommandList_Bindings.bf", "src\\Graphics\\GraphicsCommandList.bf", "src\\Graphics\\GraphicsCommandAllocator.bf", "src\\Graphics\\GraphicsCommandAllocator_Bindings.bf"]

[MainWindow]
X = 741
Y = 159
Width = 1959
Height = 1200
ShowKind = "ShowNormal"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 350.0
RequestedHeight = 200.0
SizePriority = 200.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 322.0
RequestedHeight = 200.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 115.0
TabIsPinned = false
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 150.0
RequestedHeight = 150.0
SizePriority = 150.0
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "RootSignatureFlags.bf"
TabWidth = 158.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\RootSignatureFlags.bf"
CursorPos = 570
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsRootSignature_Bindings.bf"
TabWidth = 233.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsRootSignature_Bindings.bf"
CursorPos = 207
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsRootSignature.bf"
TabWidth = 179.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsRootSignature.bf"
CursorPos = 272
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsFenceEvent_Bindings.bf"
TabWidth = 214.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsFenceEvent_Bindings.bf"
CursorPos = 207
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsFenceEvent.bf"
TabWidth = 160.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsFenceEvent.bf"
CursorPos = 347
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "FenceFlags.bf"
TabWidth = 108.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\FenceFlags.bf"
CursorPos = 152
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsFence_Bindings.bf"
TabWidth = 183.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsFence_Bindings.bf"
CursorPos = 158
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsFence.bf"
TabWidth = 129.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsFence.bf"
CursorPos = 146
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsCommandList_Bindings.bf"
TabWidth = 229.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsCommandList_Bindings.bf"
CursorPos = 242
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "CommandListType.bf"
TabWidth = 152.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\CommandListType.bf"
CursorPos = 122
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsCommandAllocator_Bindings.bf"
TabWidth = 262.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsCommandAllocator_Bindings.bf"
CursorPos = 264
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsCommandAllocator.bf"
TabWidth = 207.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsCommandAllocator.bf"
CursorPos = 400
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsDescriptorHeap.cpp"
TabWidth = 198.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "DX12\\GraphicsDescriptorHeap.cpp"
CursorPos = 244

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Disassembly"
TabWidth = 122.0
TabIsPinned = false
Type = "DisassemblyPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsDevice.bf"
TabWidth = 134.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsDevice.bf"
CursorPos = 2602
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsCPUDescriptorHandle.bf"
TabWidth = 222.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsCPUDescriptorHandle.bf"
CursorPos = 284
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsDescriptorHeap_Bindings.bf"
TabWidth = 242.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsDescriptorHeap_Bindings.bf"
CursorPos = 406
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsCommandList.bf"
TabWidth = 175.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsCommandList.bf"
CursorPos = 49
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsDescriptorHeap.bf"
TabWidth = 188.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsDescriptorHeap.bf"
CursorPos = 647
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "DescriptorHeapFlags.bf"
TabWidth = 167.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\DescriptorHeapFlags.bf"
CursorPos = 107
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "DescriptorHeapType.bf"
TabWidth = 165.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\DescriptorHeapType.bf"
CursorPos = 203
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsRenderTarget_Bindings.bf"
TabWidth = 229.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsRenderTarget_Bindings.bf"
CursorPos = 86
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsRenderTarget.bf"
TabWidth = 175.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsRenderTarget.bf"
CursorPos = 364
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsSwapChain.cpp"
TabWidth = 169.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "DX12\\GraphicsSwapChain.cpp"
CursorPos = 645

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "RenderTargetFormat.bf"
TabWidth = 165.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\RenderTargetFormat.bf"
CursorPos = 197
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsSwapChain_Bindings.bf"
TabWidth = 213.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsSwapChain_Bindings.bf"
CursorPos = 437
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsSwapChain.bf"
TabWidth = 159.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsSwapChain.bf"
CursorPos = 186
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsDevice.cpp"
TabWidth = 144.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "DX12\\GraphicsDevice.cpp"
CursorPos = 3903

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsFactory.cpp"
TabWidth = 148.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "DX12\\GraphicsFactory.cpp"
CursorPos = 2877

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "CreateResult.bf"
TabWidth = 118.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\CreateResult.bf"
CursorPos = 50
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsCommandQueue.bf"
TabWidth = 194.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsCommandQueue.bf"
CursorPos = 139
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsFactory_Bindings.bf"
TabWidth = 192.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsFactory_Bindings.bf"
CursorPos = 201
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsFactory.bf"
TabWidth = 138.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsFactory.bf"
CursorPos = 64
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsDevice_Bindings.bf"
TabWidth = 188.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsDevice_Bindings.bf"
CursorPos = 2207
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "TextUtils.bf"
TabWidth = 93.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\TextUtils.bf"
CursorPos = 364
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "KairosEditorMainWindow.bf"
TabWidth = 193.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Editors\\Windows\\KairosEditorMainWindow.bf"
CursorPos = 203
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "WindowComponents.bf"
TabWidth = 166.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\WindowComponents.bf"
CursorPos = 158
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "WindowSystem_Bindings.bf"
TabWidth = 187.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\WindowSystem_Bindings.bf"
CursorPos = 196
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "WindowSystem.bf"
TabWidth = 133.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\WindowSystem.bf"
CursorPos = 1044
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "KairosEngine.bf"
TabWidth = 121.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\KairosEngine.bf"
CursorPos = 4611
VertPos = 1665.0
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 266.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 0.4468314
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Console"
TabWidth = 97.0
TabIsPinned = false
Type = "ConsolePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Profile"
TabWidth = 87.0
TabIsPinned = false
Type = "ProfilePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 99.0
TabIsPinned = false
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 300.0

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 86.0
TabIsPinned = false
Type = "WatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs.Items]]
EvalStr = ""

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Auto"
TabWidth = 77.0
TabIsPinned = false
Type = "AutoWatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 0.5531687
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 97.0
TabIsPinned = false
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 105.0
TabIsPinned = false
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Immediate"
TabWidth = 111.0
TabIsPinned = false
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Output"
TabWidth = 90.0
TabIsPinned = false
Type = "OutputPanel"

[[BookmarkFolders]]
Title = ""

[OutputFilters]
ModuleLoadMessages = false
ModuleUnloadMessages = false
ProcessExitMessages = false
ThreadCreateMessages = false
ThreadExitMessages = false
SymbolLoadMessages = false
ProgramOutput = false
