FileVersion = 1
LastConfig = "Release"
LastPlatform = "Win64"
RecentFilesList = ["src\\ImGUI\\ImGuiDX12.bf", "src\\Graphics\\GraphicsFactory.bf", "src\\ImGUI\\ImGuiDX12Data.bf", "src\\Graphics\\GraphicsDevice.bf", "src\\ImGUI\\ImGuiDX12RenderBuffers.bf", "src\\Graphics\\GraphicsDevice_Bindings.bf", "src\\Graphics\\GraphicsRootSignatureDesc.bf", "src\\Graphics\\StaticBorderColor.bf", "src\\Graphics\\GraphicsStaticSamplerDesc.bf", "src\\Graphics\\ComparisonFunc.bf", "src\\Graphics\\TextureAddressMode.bf", "src\\Graphics\\SamplerFilter.bf", "src\\Graphics\\GraphicsRootDescriptor.bf", "src\\Graphics\\ShaderVisibility.bf", "src\\Graphics\\GraphicsRootDescriptorTable.bf", "src\\Graphics\\GraphicsRootParameter.bf", "src\\Graphics\\RootParameterType.bf", "src\\Graphics\\GraphicsRootConstants.bf", "src\\Graphics\\GraphicsDescriptorRange.bf", "src\\Graphics\\DescriptorRangeType.bf"]

[MainWindow]
X = 824
Y = 424
Width = 1649
Height = 1068
ShowKind = "ShowNormal"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 350.0
RequestedHeight = 200.0
SizePriority = 200.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 409.0
RequestedHeight = 200.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 115.0
TabIsPinned = false
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 150.0
RequestedHeight = 150.0
SizePriority = 150.0
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "ImGuiDX12RenderBuffers.bf"
TabWidth = 201.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\ImGUI\\ImGuiDX12RenderBuffers.bf"
CursorPos = 252
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "ImGuiDX12Data.bf"
TabWidth = 146.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\ImGUI\\ImGuiDX12Data.bf"
CursorPos = 146
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsDevice.bf"
TabWidth = 144.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsDevice.bf"
CursorPos = 261
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsDevice_Bindings.bf"
TabWidth = 198.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsDevice_Bindings.bf"
CursorPos = 2863
VertPos = 90.0
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsRootSignatureDesc.bf"
TabWidth = 217.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsRootSignatureDesc.bf"
CursorPos = 166
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "StaticBorderColor.bf"
TabWidth = 157.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\StaticBorderColor.bf"
CursorPos = 164
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "ComparisonFunc.bf"
TabWidth = 152.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\ComparisonFunc.bf"
CursorPos = 218
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "TextureAddressMode.bf"
TabWidth = 180.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\TextureAddressMode.bf"
CursorPos = 130
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "SamplerFilter.bf"
TabWidth = 130.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\SamplerFilter.bf"
CursorPos = 1062
VertPos = 135.0
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsStaticSamplerDesc.bf"
TabWidth = 213.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsStaticSamplerDesc.bf"
CursorPos = 64
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsRootDescriptor.bf"
TabWidth = 194.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsRootDescriptor.bf"
CursorPos = 161
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsRootConstants.bf"
TabWidth = 191.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsRootConstants.bf"
CursorPos = 57
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsRootDescriptorTable.bf"
TabWidth = 226.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsRootDescriptorTable.bf"
CursorPos = 149
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "ShaderVisibility.bf"
TabWidth = 143.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\ShaderVisibility.bf"
CursorPos = 153
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsRootParameter.bf"
TabWidth = 193.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsRootParameter.bf"
CursorPos = 276
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "RootParameterType.bf"
TabWidth = 171.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\RootParameterType.bf"
CursorPos = 47
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsDescriptorRange.bf"
TabWidth = 204.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsDescriptorRange.bf"
CursorPos = 294
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "DescriptorRangeType.bf"
TabWidth = 181.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\DescriptorRangeType.bf"
CursorPos = 163
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsFactory.bf"
TabWidth = 148.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsFactory.bf"
CursorPos = 320
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsFeature.bf"
TabWidth = 149.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsFeature.bf"
CursorPos = 107
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsFactory_Bindings.bf"
TabWidth = 202.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsFactory_Bindings.bf"
CursorPos = 1110
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "CrashCatcher.cpp"
TabWidth = 141.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "d:\\BeefSource\\Beef\\BeefySysLib\\platform\\win\\CrashCatcher.cpp"
CursorPos = 32446
VertPos = 16920.0

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "ImGui_Extensions.bf"
TabWidth = 154.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "ImGUIs\\imgui-beef\\src\\ImGui_Extensions.bf"
CursorPos = 890
VertPos = 225.0
ProjectName = "ImGui"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "ImGui.bf"
TabWidth = 88.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "ImGUIs\\imgui-beef\\src\\ImGui.bf"
CursorPos = 308175
VertPos = 106350.0
ProjectName = "ImGui"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "ErrorCodes.bf"
TabWidth = 112.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\ImGUI\\ErrorCodes.bf"
CursorPos = 106
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "ImGuiDX12.bf"
TabWidth = 109.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\ImGUI\\ImGuiDX12.bf"
CursorPos = 2530
VertPos = 894.0
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "ImGuiDescriptorHeapAllocator.bf"
TabWidth = 221.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\ImGUI\\ImGuiDescriptorHeapAllocator.bf"
CursorPos = 921
VertPos = 51.0
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Internal.cpp"
TabWidth = 98.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "d:\\BeefSource\\Beef\\BeefRT\\rt\\Internal.cpp"
CursorPos = 11763

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsSwapChain.bf"
TabWidth = 159.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsSwapChain.bf"
CursorPos = 723
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsSwapChain_Bindings.bf"
TabWidth = 213.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsSwapChain_Bindings.bf"
CursorPos = 795
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsRenderTarget.bf"
TabWidth = 175.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsRenderTarget.bf"
CursorPos = 116
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsCommandAllocator.bf"
TabWidth = 207.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsCommandAllocator.bf"
CursorPos = 335
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsCommandAllocator_Bindings.bf"
TabWidth = 262.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsCommandAllocator_Bindings.bf"
CursorPos = 91
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsFenceEvent.bf"
TabWidth = 160.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsFenceEvent.bf"
CursorPos = 149
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Kernel.bf"
TabWidth = 82.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Kernel.bf"
CursorPos = 346
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "WindowSystem_Bindings.bf"
TabWidth = 187.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\WindowSystem_Bindings.bf"
CursorPos = 184
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsFence_Bindings.bf"
TabWidth = 183.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsFence_Bindings.bf"
CursorPos = 513
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsFenceEvent_Bindings.bf"
TabWidth = 214.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsFenceEvent_Bindings.bf"
CursorPos = 514
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsFence.bf"
TabWidth = 129.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsFence.bf"
CursorPos = 228
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "WindowSystem.bf"
TabWidth = 133.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\WindowSystem.bf"
CursorPos = 880
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Rect.bf"
TabWidth = 70.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\Rect.bf"
CursorPos = 265
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "ViewPort.bf"
TabWidth = 96.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\ViewPort.bf"
CursorPos = 380
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsResource_Bindings.bf"
TabWidth = 204.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsResource_Bindings.bf"
CursorPos = 346
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsResource.bf"
TabWidth = 150.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsResource.bf"
CursorPos = 203
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsVertexBufferView.bf"
TabWidth = 194.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsVertexBufferView.bf"
CursorPos = 380
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsCommandQueue.bf"
TabWidth = 194.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsCommandQueue.bf"
CursorPos = 335
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsCommandQueue_Bindings.bf"
TabWidth = 248.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsCommandQueue_Bindings.bf"
CursorPos = 653
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsCommandList.bf"
TabWidth = 175.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsCommandList.bf"
CursorPos = 524
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsCommandList_Bindings.bf"
TabWidth = 229.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Graphics\\GraphicsCommandList_Bindings.bf"
CursorPos = 418
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "KairosEngine.bf"
TabWidth = 121.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\KairosEngine.bf"
CursorPos = 4586
VertPos = 2220.0
ProjectName = "KairosEngine"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 1914.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Console"
TabWidth = 97.0
TabIsPinned = false
Type = "ConsolePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 99.0
TabIsPinned = false
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 300.0

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 86.0
TabIsPinned = false
Type = "WatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs.Items]]
EvalStr = ""

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Auto"
TabWidth = 77.0
TabIsPinned = false
Type = "AutoWatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 1914.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Find Results"
TabWidth = 119.0
TabIsPinned = false
Type = "FindResultsPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 97.0
TabIsPinned = false
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 105.0
TabIsPinned = false
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 111.0
TabIsPinned = false
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Output"
TabWidth = 90.0
TabIsPinned = false
Type = "OutputPanel"

[[BookmarkFolders]]
Title = ""

[OutputFilters]
ModuleLoadMessages = false
ModuleUnloadMessages = false
ProcessExitMessages = false
ThreadCreateMessages = false
ThreadExitMessages = false
SymbolLoadMessages = false
ProgramOutput = false
